### PR TITLE
Add (public) project listing page

### PR DESCRIPTION
**Pull request by McSinyx**

### CODE REVIEW

**Review by Huy-Ngo — DISMISSED** [review]
I don't see any problem with the implemented site.

**Review by 9a24f0 — DISMISSED** [review]

**Comment by McSinyx** [comment]
Oh boy there's a conflict, let me resolve it first :sweat_smile:  For the moment, maybe GH-87 should be given some priority since it changes the underlying data repr.

**Comment by McSinyx** [comment]
Gentle ping for re-re-view!

**Review by Huy-Ngo — APPROVED** [review]

**Review by DDHLong — APPROVED** [review]

**Comment by McSinyx** [comment]
Thanks!

**Pull request merged**
