### PR TITLE
Split database document for clarification

### LINKED ISSUE #148: Document about database does not represent the database
As of now the document about the database only describes the structure of different entity sets/classes and their relations, but not how many and which tables are stored in the database. It may give a false impression that each entity set is represented by a database table, which is not true.

### PR DESCRIPTION
**Pull request by Huy-Ngo**
Resolve #148

### CODE REVIEW

**Comment by Huy-Ngo** [comment]
Yay

**Review by McSinyx — APPROVED** [review]
Please enlighten me why you need the SVG *and* the plantuml though :smile:  My sysadmin energy is draining ATM so I'm not going to look into it myself.

**Comment by Huy-Ngo** [comment]
> Please enlighten me why you need the SVG and the plantuml though

The SVG file is to be imported, of course (I don't think plantuml 2020.21 is packed for sourcehut's images yet). The puml file there so if one wants to edit one can go to plantuml.com to edit and regenerate it oneself.

**Comment by Huy-Ngo** [comment]
So weird, why does the test pass here but not in main.

**Pull request merged**
