### PR TITLE
Implement project begin-end time in UI

### LINKED ISSUE #212: Type hint RethinkDB driver properly
Currently we're using Any for most of the methods, which is pretty much the equivalent of `# type: ignore` and thus we don't really benefit from any static type checking.

### PR DESCRIPTION
**Pull request by McSinyx**
Project listings templates are merged together for maintainability.

This accidentally fixes #212.

### CODE REVIEW

**Review by DDHLong — APPROVED** [review]

**Comment by McSinyx** [comment]
Thanks!

**Comment by Huy-Ngo** [comment]
@McSinyx This one seems to cause trouble -- I couldn't view `/p/` with an exception: `jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'created_on'`

**Comment by McSinyx** [comment]
Do you have any project created after pulling this?  Manually add the `created_on` field to each of them would help.

**Comment by Huy-Ngo** [comment]
On Fri, 19 Feb 2021, 17:42 Nguyễn Gia Phong, <notifications@github.com>
wrote:

> Do you have any project created after pulling this? Manually add the
> created_on field to each of them would help.
>
There are, and they do have created_on field.

>

**Comment by Huy-Ngo** [comment]
On Fri, Feb 19, 2021 at 6:40 PM Huy Ngo <duchuy29092000@gmail.com> wrote:
>
> There are, and they do have created_on field.

Sorry, it seems that was just one instance not having it.

**Comment by Huy-Ngo** [comment]
Anyway, shouldn't the time be absolute rather than relative like this?

**Comment by McSinyx** [comment]
> Anyway, shouldn't the time be absolute rather than relative like this?

Yea it doesn't make much sense for creation time and deadlines of projects.  PR incoming.

**Pull request merged**
