### PR TITLE
Archive paper

### PR DESCRIPTION
**Pull request by McSinyx**
Since we're submitted the report, there's no point running the CI/CD for it, plus we should make room for actual documentation.  Latest build downloaded from sr.ht is archived to `paper/build/latex/acanban.pdf`.

To provide the context, the following issues are to be closed along with this PR:

- Close GH-103
- Close GH-133
- Close GH-163
- Close GH-165
- Close GH-193
- Close GH-205
- Close GH-219
- Close GH-221
- Close GH-222

Imma go ahead and close the Documentation project.

### CODE REVIEW

**Comment by Huy-Ngo** [comment]
Is the pdf file backed up?

**Comment by McSinyx** [comment]
Yes, in paper/build/latex/acanban.pdf
(ya many files are moved, it's not obvious).

**Comment by Huy-Ngo** [comment]
> paper/build/latex/acanban.pdf

But that file is shown as empty.

**Comment by McSinyx** [comment]
Let's say GitHub is trying to be smart where it shouldn't.
It's definitely not empty (-;

**Review by Huy-Ngo — APPROVED** [review]
OK then lol

**Pull request merged**
