### PR TITLE
Use 2ndary index instead of double ref

### PR DESCRIPTION
**Pull request by McSinyx**
Sorry for not opening a tracking ticket, Agile god!

### CODE REVIEW

**Review by Huy-Ngo — APPROVED** [review]
Seems good

**Comment by Huy-Ngo** [comment]
There are lint issues tho

**Review by Huy-Ngo — CHANGES_REQUESTED** [review]
Fix the lints first:

```
./src/acanban/project.py:23:1: F401 'typing.Optional' imported but unused
./src/acanban/db.py:19:1: F401 'typing.Dict' imported but unused
```

**Comment by McSinyx** [comment]
Ah thanks, did not notice that.

**Review by Huy-Ngo — APPROVED** [review]

**Pull request merged**
