### PR TITLE
Always use UTC

### PR DESCRIPTION
**Pull request by McSinyx**
Enforce UTC, because timezone in internal data has caused me too many headaches.  I bumped the version because we've made enough changes to the database schema so far that should be applied on the test server, before there are too many to cause integration issues.

### CODE REVIEW

**Comment by McSinyx** [comment]
Note that in areas with DST, local UTC offset will only be accurate 50% of the time.  I'll add a field for user's timezone if this patch is accepted, and use dateutil for handling in time formatting.

**Comment by Huy-Ngo** [comment]
Dammit why did they have to invent DST???

**Comment by McSinyx** [comment]
If you have the time (pun unintended), I recommend watching this:
https://www.youtube.com/watch?v=rz3D8VG_2TY

**Review by Huy-Ngo — CHANGES_REQUESTED** [review]
When I create a comment it's 7 hours ago.
image

**Review by Huy-Ngo — APPROVED** [review]
Nvm I didn't checkout

**Pull request merged**
