### PR TITLE
Require 100% test coverage

### PR DESCRIPTION
**Pull request by McSinyx**
When this is merged, it should be safe to close GH-10.

The package dir is moved to play nicely with coverage.py.  To quote [Trio's contrib guide](https://trio.readthedocs.io/en/stable/contributing.html#tests):

> Every change should have 100% coverage for both code and tests.  But, you can use `# pragma: no cover` to mark lines where lack-of-coverage isn’t something that we’d want to fix (as opposed to it being merely hard to fix).

### CODE REVIEW

**Comment by 9a24f0** [comment]
ugh, 100% coverage?

**Comment by McSinyx** [comment]
Yes, let's see how it'll go :upside_down_face:  I'll need to bump cov to 100% first in order for this to pass :smile:  The requirement has more to do with how conscious we are with what are tested, rather than having a lot of tests.

**Comment by Huy-Ngo** [comment]
Some tests, failed, only 85% coverage 😬

**Comment by McSinyx** [comment]
58, it was 58%.  It's 100 now, although a bit forced.

**Review by Huy-Ngo — APPROVED** [review]
LGTM

**Comment by McSinyx** [comment]
May I have another review?

**Review by 9a24f0 — APPROVED** [review]
LGTM!

**Pull request merged**
