### PR TITLE
Implement task creation

### PR DESCRIPTION
**Pull request by McSinyx**
Resolve GH-110.

### CODE REVIEW

**Comment by Huy-Ngo** [comment]
> need eyes

:eyes: Here you go :eye:

**Comment by Huy-Ngo** [comment]
> Also enforce UTC

That's ok as long as you display the time according to the user's timezone.

**Comment by McSinyx** [comment]
But what's the user's timezone?  That'd require an additional field
User object, which I'd prefer to be done in another patch.

**Comment by Huy-Ngo** [comment]
I think setting timezone to the host timezone (i.e. school timezone) is the best solution. Otherwise client timezone can be detected by JS.

**Comment by McSinyx** [comment]
I moved the tz thing to GH-236 to focus on more urgent matters.

**Review by Huy-Ngo — APPROVED** [review]
It's working fine

**Comment by McSinyx** [comment]
I'm glad to hear.

**Pull request merged**
